### ISSUE TITLE
!inspire randomly fails

### ISSUE THREAD

**Issue by aceat64** [Waifus4Lifu/waifu-bot#88]
When it does fail, the following error is generated:

```
Aug 15 11:21:44 cayde-6 python3.6[24877]: Ignoring exception in on_command_error
Aug 15 11:21:44 cayde-6 python3.6[24877]: Traceback (most recent call last):
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/usr/local/lib/python3.6/dist-packages/PIL/ImagePalette.py", line 97, in getcolor
Aug 15 11:21:44 cayde-6 python3.6[24877]:     return self.colors[color]
Aug 15 11:21:44 cayde-6 python3.6[24877]: KeyError: (0, 0, 0)
Aug 15 11:21:44 cayde-6 python3.6[24877]: During handling of the above exception, another exception occurred:
Aug 15 11:21:44 cayde-6 python3.6[24877]: Traceback (most recent call last):
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 251, in _run_event
Aug 15 11:21:44 cayde-6 python3.6[24877]:     await coro(*args, **kwargs)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/home/waifus/waifu-bot/bot.py", line 474, in on_command_error
Aug 15 11:21:44 cayde-6 python3.6[24877]:     raise error.original
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
Aug 15 11:21:44 cayde-6 python3.6[24877]:     ret = await coro(*args, **kwargs)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/home/waifus/waifu-bot/bot.py", line 787, in inspire
Aug 15 11:21:44 cayde-6 python3.6[24877]:     image = draw.inspiration(id, text, name, query, comical)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/home/waifus/waifu-bot/draw.py", line 166, in inspiration
Aug 15 11:21:44 cayde-6 python3.6[24877]:     draw_text(img, text, xy, font, "center", "white", "black", border_width)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/home/waifus/waifu-bot/draw.py", line 220, in draw_text
Aug 15 11:21:44 cayde-6 python3.6[24877]:     draw.text(xy=xy_border, text=text, font=font, align=align, fill=border_color)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/usr/local/lib/python3.6/dist-packages/PIL/ImageDraw.py", line 212, in text
Aug 15 11:21:44 cayde-6 python3.6[24877]:     *args, **kwargs)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/usr/local/lib/python3.6/dist-packages/PIL/ImageDraw.py", line 250, in multiline_text
Aug 15 11:21:44 cayde-6 python3.6[24877]:     direction=direction, features=features)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/usr/local/lib/python3.6/dist-packages/PIL/ImageDraw.py", line 213, in text
Aug 15 11:21:44 cayde-6 python3.6[24877]:     ink, fill = self._getink(fill)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/usr/local/lib/python3.6/dist-packages/PIL/ImageDraw.py", line 111, in _getink
Aug 15 11:21:44 cayde-6 python3.6[24877]:     ink = self.palette.getcolor(ink)
Aug 15 11:21:44 cayde-6 python3.6[24877]:   File "/usr/local/lib/python3.6/dist-packages/PIL/ImagePalette.py", line 107, in getcolor
Aug 15 11:21:44 cayde-6 python3.6[24877]:     self.palette[index+256] = color[1]
Aug 15 11:21:44 cayde-6 python3.6[24877]: IndexError: bytearray index out of range
```

**Comment by davidecotten** [comment]
Fixed by #96
